/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    aktorzy: Aktorzy;
    jezyki: Jezyki;
    spiewy: Spiewy;
    tancy: Tancy;
    instrumenty: Instrumenty;
    pages: Page;
    users: User;
    media: Media;
    examples: Example;
  };
  globals: {
    'main-menu': MainMenu;
  };
}
export interface Aktorzy {
  id: string;
  kategoria?: 'aktorzy' | 'aktorki' | 'mlodzi';
  imie: string;
  nazwisko: string;
  pesel: number;
  nrDowodu: string;
  daneBankowe: {
    bank: string;
    numerKonta: number;
  };
  imionaRodzicow: string;
  dataUrodzenia: string;
  miejsceUrodzenia: string;
  adres: {
    ulica: string;
    numer: string;
    nrMieszkania?: string;
    kodPocztowy: string;
    miasto: string;
  };
  urzadSkrabowy: number;
  szkola?: {
    szkola?: boolean;
    nazwaSzkoly?: string;
    rok?: string;
    rokUkonczenia?: string;
  };
  etat?: {
    etat?: boolean;
    teatr?: string;
  };
  kolorWlosow?: string;
  dlugoscWlosow?: string;
  kolorOczu?: string;
  wzrost?: number;
  kolnierzyk?: number;
  klatkaPiersiowa?: number;
  pas?: number;
  biodra?: number;
  numerButa?: number;
  rozmiarUbran?: number;
  rozmiarGarnituru?: number;
  rozmiarDzinsow?: number;
  prawoJazdy?: boolean;
  jezyki?: {
    jezykiObcy?: boolean;
    jezyki?: {
      language?: string | Jezyki;
      poziom?: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
      id?: string;
    }[];
  };
  spiewy?: {
    spiew?: boolean;
    spiewy?: {
      spiew?: string | Spiewy;
      id?: string;
    }[];
  };
  tancy?: {
    taniec?: boolean;
    tancy?: {
      taniec?: string | Tancy;
      id?: string;
    }[];
  };
  instrumenty?: {
    instrument?: boolean;
    instrumenty?: {
      instrument?: string | Instrumenty;
      id?: string;
    }[];
  };
  umiejetnosci?: string;
  nagrody?: string;
  filmografia?: {
    film?: {
      rok?: string;
      tytul?: string;
      najwazniejszeRoly?: string;
    };
    id?: string;
  }[];
  filmpolski?: string;
  youtube?: string;
  instagram?: string;
  www?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Jezyki {
  id: string;
  jezyk: string;
  updatedAt: string;
  createdAt: string;
}
export interface Spiewy {
  id: string;
  spiew: string;
  updatedAt: string;
  createdAt: string;
}
export interface Tancy {
  id: string;
  taniec: string;
  updatedAt: string;
  createdAt: string;
}
export interface Instrumenty {
  id: string;
  instrument: string;
  updatedAt: string;
  createdAt: string;
}
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText: {
      [k: string]: unknown;
    }[];
    links?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference: {
          value: string | Page;
          relationTo: 'pages';
        };
        url: string;
        label: string;
        appearance?: 'default' | 'primary' | 'secondary';
      };
      id?: string;
    }[];
    media: string | Media;
  };
  layout: (
    | {
        ctaBackgroundColor?: 'white' | 'black';
        richText: {
          [k: string]: unknown;
        }[];
        links?: {
          link: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              value: string | Page;
              relationTo: 'pages';
            };
            url: string;
            label: string;
            appearance?: 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        contentBackgroundColor?: 'white' | 'black';
        layout?: 'oneColumn' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
        columnOne: {
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              value: string | Page;
              relationTo: 'pages';
            };
            url: string;
            label: string;
            appearance?: 'default' | 'primary' | 'secondary';
          };
        };
        columnTwo?: {
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              value: string | Page;
              relationTo: 'pages';
            };
            url: string;
            label: string;
            appearance?: 'default' | 'primary' | 'secondary';
          };
        };
        columnThree?: {
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              value: string | Page;
              relationTo: 'pages';
            };
            url: string;
            label: string;
            appearance?: 'default' | 'primary' | 'secondary';
          };
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        mediaBlockBackgroundColor?: 'white' | 'black';
        position?: 'default' | 'fullscreen';
        media: string | Media;
        caption?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
  )[];
  slug?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Example {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
}
export interface MainMenu {
  id: string;
  navItems?: {
    link: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference: {
        value: string | Page;
        relationTo: 'pages';
      };
      url: string;
      label: string;
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
